### ISSUE TITLE
Start rate settings in the Poseidon paper

### ISSUE THREAD

**Issue by snow276** [Clark5/Poseidon#1]
Hello! I'm trying to repeat the experiments in the Poseidon paper with this ns3 code. However, I'm confused about the start rate settings in this repo when I'm reading through the code.

In this repo, Poseidon seems to start sending at a low rate (by denoting `qp->poseidon.m_curRate= m_bps /100.0;`  in `rdma-hw.cc`), while HPCC seems to start sending at line rate (by denoting `hp.m_curRate = m_bps;` in `rdma-hw.cc`). 

However, it seems that all congestion control algorithms start sending at a low rate in the experiements in the Poseidon paper (as shown in Figure 17(a) in the paper).

Therefore, I am wondering: Can I reproduce the experiment results with the given start rate settings in this repo? If there is any problem with it, could you please provide the starting rate settings you used in the experiments in the Poseidon paper?

Thank you very much!

**Comment by Clark5** [comment]
Hi Snow, thank you for your question. Figure 17(a) in the Poseidon paper uses a 200 Gbps link. It shows how a second flow ramps up its rate when there is already one flow that fully utilizes the bandwidth. I think this is the part where you get confused.

====================================
PS1: You can always change the initial sending rate for any CC algorithm in the simulator.
PS2: Poseidon paper uses an omnet++ simulator, which is a Google internal codebase and it has a slight performance difference with the NS3 one, but not anything with huge differences.

**Comment by snow276** [comment]
Thank you for your explanation!
